### ISSUE TITLE
Is this driver production ready?

### ISSUE THREAD

**Issue by mewis** [omixen/gorm-snowflake#14]
Hi @omixen, This looks really interesting and exactly what I was looking for as I am converting my data warehouse from mysql to snowflake and already have gorm in place.
Do you believe this will be an active project and if so do you reckon this is production ready.
Thank you for your hard work.

**Comment by omixen** [comment]
Hi @mewis we are using this driver in production for basic functionality (i.e. no fancy structure, just need to upsert some rows)

In the main README, I described the decisions that were made to make this driver works considering Snowflake set of features or lack of features. I have a change that need to be pushed to the main gorm repo to skip non-applicable tests for Snowflake.

Feel free to pull this down and use it in your scenario, if you encounter any issue, just file an issue, and I can take a look.
As Snowflake is cloud-based, you would have to BYO instance to test this out. Let me know if you need help setting it up.

Cheers

**Comment by mewis** [comment]
Thats great, I will thank you.
