### ISSUE TITLE
gorm-snowflake breaks with recent change to GORM

### ISSUE THREAD

**Issue by bgtill** [omixen/gorm-snowflake#19]
GORM Introduced a breaking change here: https://github.com/go-gorm/gorm/pull/5736
[This PR](https://github.com/omixen/gorm-snowflake/pull/18) makes changes to mitigate that issue. A similar approach was
taken here:

https://github.com/go-gorm/sqlserver/pull/70
https://github.com/go-gorm/sqlite/pull/114

**Comment by omixen** [comment]
Closed by #18
